[platformio]
default_envs = stable # set to wokwi for simulation

[env:stable]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    https://github.com/adafruit/DHT-sensor-library
board_build.partitions = src/partitions.csv
board_build.filesystem = littlefs
board_build.flash_mode = qio

[env:esp32c3]
extends = env:stable
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

board = esp32-c3-devkitm-1
# enhance risc-v stack unwind
build_flags = 
    -funwind-tables

[env:esp32c3_super_mini]
extends = env:esp32c3

board = nologo_esp32c3_super_mini

# enhance risc-v stack unwind
build_flags = 
    -funwind-tables
    -DNOLOGO_C3_SUPER_MINI
upload_protocol = esptool

[env:esp32c3_super_mini_noled]
extends = env:esp32c3_super_mini

build_flags = 
    -funwind-tables
    -DNOLOGO_C3_SUPER_MINI
    -DNO_LED_FLASHING

[env:wokwi]
extends = env:stable
build_flags = 
    -D USING_WOKWI=1

[env:wokwi-c3-mini]
extends = env:esp32c3
build_flags = 
    -D USING_WOKWI=1