[platformio]
default_envs = stable # set to wokwi for simulation

[env:stable]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    https://github.com/adafruit/DHT-sensor-library
board_build.partitions = src/partitions.csv
board_build.filesystem = littlefs
board_build.flash_mode = qio

[env:wokwi]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    https://github.com/adafruit/DHT-sensor-library
build_flags = 
    -D USING_WOKWI=1

[env:wokwi-c3-mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = nologo_esp32c3_super_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    https://github.com/adafruit/DHT-sensor-library
build_flags = 
    -D USING_WOKWI=1

[env:esp32c3_super_mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

board = nologo_esp32c3_super_mini
board_build.partitions = src/partitions.csv
board_build.filesystem = spiffs
board_build.flash_mode = qio

framework = arduino
monitor_speed = 115200

# enhance risc-v stack unwind
build_flags = 
    -funwind-tables
lib_deps =
    https://github.com/adafruit/DHT-sensor-library

upload_protocol = esp-builtin
upload_speed = 921600


[env:esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

board = esp32-c3-devkitm-1
board_build.partitions = src/partitions.csv
board_build.filesystem = spiffs
board_build.flash_mode = qio

framework = arduino
monitor_speed = 115200

# enhance risc-v stack unwind
build_flags = 
    -funwind-tables
lib_deps =
    https://github.com/adafruit/DHT-sensor-library

upload_protocol = esp-builtin
upload_speed = 921600
